/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package otomasyon.kutuphane;

import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mcahi
 */
public class anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form anasayfa
     */
    public anasayfa() {
        initComponents();
    }
    anasayfa(JPanel jPanel1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void search(String srt){
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        TableRowSorter<DefaultTableModel> trs =new TableRowSorter<>(model);
        urun_tablosu.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(srt));
        DefaultTableModel model1 = (DefaultTableModel) urun_tablosu1.getModel();
        TableRowSorter<DefaultTableModel> trs1 =new TableRowSorter<>(model1);
        urun_tablosu1.setRowSorter(trs1);
        trs1.setRowFilter(RowFilter.regexFilter(srt));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        anasayfa = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kutuphane = new javax.swing.JPanel();
        tf_urun_ismi = new javax.swing.JTextField();
        tf_yazar = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox<>();
        tf_stok = new javax.swing.JTextField();
        ekle_butonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();
        tf_arama = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        oduncal = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        urun_tablosu1 = new javax.swing.JTable();
        tf_arama1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_iade = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        odunc_tablo = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btn_odunc = new javax.swing.JButton();
        tf_kitap1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tf_yazar1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        date2 = new com.toedter.calendar.JDateChooser();
        date1 = new com.toedter.calendar.JDateChooser();
        cb_kategori1 = new javax.swing.JComboBox<>();
        mesaj_yazisi1 = new javax.swing.JLabel();
        kullanici = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        kullanici_tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(14, 151, 137));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-home-50.png")); // NOI18N
        jLabel1.setText("ANASAYFA");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setText("Kütüphane-Master v 1.0'a");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-register-64 (1).png")); // NOI18N
        jLabel3.setText("ÖDÜNÇ AL - İADE ET ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-book-50.png")); // NOI18N
        jLabel4.setText("KÜTÜPHANE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-open-book-50.png")); // NOI18N
        jLabel5.setText("KULLANICILAR");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-exit-48.png")); // NOI18N
        jLabel6.setText("ÇIKIŞ");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel26.setText("HOŞGELDİNİZ!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(18, 18, 18))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(94, 94, 94)
                .addComponent(jLabel6)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 960);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1650, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 1650, 60);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("MÜCAHİT YILMAZ ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-github-90.png")); // NOI18N
        jLabel15.setText("github.com/tegwen34");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-mail-100.png")); // NOI18N
        jLabel16.setText(" mucahittylmz34@gmail.com");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\3893093-200.png")); // NOI18N
        jLabel17.setText("DÜZCE ÜNİVERSİTESİ/ELEKTRİK-ELEKTRONİK MÜHENDİSLİĞİ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(441, 441, 441))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(507, 507, 507))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel16))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 131, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(123, 123, 123)
                .addComponent(jLabel14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addContainerGap(207, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout anasayfaLayout = new javax.swing.GroupLayout(anasayfa);
        anasayfa.setLayout(anasayfaLayout);
        anasayfaLayout.setHorizontalGroup(
            anasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, anasayfaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        anasayfaLayout.setVerticalGroup(
            anasayfaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anasayfaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", anasayfa);

        kutuphane.setBackground(new java.awt.Color(255, 255, 255));

        tf_yazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_yazarActionPerformed(evt);
            }
        });

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roman", "Tiyatro", "Tarih", "Psikoloji", "Biyografi", "Ansiklopedi", " ", " " }));

        tf_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_stokActionPerformed(evt);
            }
        });

        ekle_butonu.setText("Kitap Ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        guncelle_butonu.setText("Kitap Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        sil_butonu.setText("Kitap Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        tf_arama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_aramaActionPerformed(evt);
            }
        });
        tf_arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_aramaKeyReleased(evt);
            }
        });

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitaplar", "Kategori", "Yazar", "Sayfa Sayısı"
            }
        ));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        jLabel7.setText("Kitap ismi:");

        jLabel8.setText("Yazar:");

        jLabel9.setText("Kategori:");

        jLabel10.setText("Sayfa Sayısı:");

        jLabel25.setText("Kitap Arama:");

        javax.swing.GroupLayout kutuphaneLayout = new javax.swing.GroupLayout(kutuphane);
        kutuphane.setLayout(kutuphaneLayout);
        kutuphaneLayout.setHorizontalGroup(
            kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kutuphaneLayout.createSequentialGroup()
                .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(30, 30, 30)
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_kategori, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                                .addComponent(tf_urun_ismi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_yazar, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel25))
                        .addGap(259, 259, 259)
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guncelle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sil_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kutuphaneLayout.createSequentialGroup()
                            .addGap(234, 234, 234)
                            .addComponent(tf_arama, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kutuphaneLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(345, Short.MAX_VALUE))
        );
        kutuphaneLayout.setVerticalGroup(
            kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kutuphaneLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_urun_ismi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ekle_butonu))
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_yazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(sil_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guncelle_butonu)
                            .addComponent(jLabel9)
                            .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(114, 114, 114)
                .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kutuphaneLayout.createSequentialGroup()
                        .addGroup(kutuphaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_arama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", kutuphane);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        urun_tablosu1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitaplar", "Kategori", "Yazar", "Sayfa Sayısı"
            }
        ));
        urun_tablosu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosu1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(urun_tablosu1);

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(600, 140, 582, 350);

        tf_arama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_arama1ActionPerformed(evt);
            }
        });
        tf_arama1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_arama1KeyReleased(evt);
            }
        });
        jPanel9.add(tf_arama1);
        tf_arama1.setBounds(830, 100, 263, 22);

        jLabel18.setText("Kitap Arama:");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(690, 100, 68, 16);

        btn_iade.setText("İade et");
        btn_iade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iadeActionPerformed(evt);
            }
        });
        jPanel9.add(btn_iade);
        btn_iade.setBounds(380, 630, 99, 22);

        odunc_tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kitap", "Yazar", "Kategori", "Alınma Tarihi", "Teslim Tarihi"
            }
        ));
        jScrollPane3.setViewportView(odunc_tablo);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(10, 140, 580, 350);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel11.setText("KİTAPLAR");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(830, 10, 227, 64);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel19.setText("ALINAN KİTAPLAR");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(90, 10, 424, 64);

        jLabel20.setText("Kitap İsmi:");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(50, 510, 55, 16);

        btn_odunc.setText("Ödünç Al");
        btn_odunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oduncActionPerformed(evt);
            }
        });
        jPanel9.add(btn_odunc);
        btn_odunc.setBounds(380, 560, 100, 22);

        tf_kitap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kitap1ActionPerformed(evt);
            }
        });
        jPanel9.add(tf_kitap1);
        tf_kitap1.setBounds(140, 510, 190, 22);

        jLabel21.setText("Teslim Tarihi:");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(30, 670, 69, 16);

        jLabel22.setText("Yazar İsmi:");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(50, 550, 56, 16);

        jLabel23.setText("Kategori:");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(60, 590, 47, 16);

        tf_yazar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_yazar1ActionPerformed(evt);
            }
        });
        jPanel9.add(tf_yazar1);
        tf_yazar1.setBounds(140, 550, 190, 22);

        jLabel24.setText("Alınma Tarihi:");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(30, 630, 73, 16);
        jPanel9.add(date2);
        date2.setBounds(140, 670, 190, 22);
        jPanel9.add(date1);
        date1.setBounds(140, 630, 190, 22);

        cb_kategori1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roman", "Tiyatro", "Tarih", "Psikoloji", "Biyografi", "Ansiklopedi", " ", " " }));
        jPanel9.add(cb_kategori1);
        cb_kategori1.setBounds(140, 590, 190, 22);
        jPanel9.add(mesaj_yazisi1);
        mesaj_yazisi1.setBounds(320, 110, 270, 20);

        javax.swing.GroupLayout oduncalLayout = new javax.swing.GroupLayout(oduncal);
        oduncal.setLayout(oduncalLayout);
        oduncalLayout.setHorizontalGroup(
            oduncalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oduncalLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        oduncalLayout.setVerticalGroup(
            oduncalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oduncalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", oduncal);

        kullanici.setBackground(new java.awt.Color(255, 255, 255));

        kullanici_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kullanıcı adı", "Parola"
            }
        ));
        kullanici_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kullanici_tbMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(kullanici_tb);

        javax.swing.GroupLayout kullaniciLayout = new javax.swing.GroupLayout(kullanici);
        kullanici.setLayout(kullaniciLayout);
        kullaniciLayout.setHorizontalGroup(
            kullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        kullaniciLayout.setVerticalGroup(
            kullaniciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullaniciLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", kullanici);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(417, 0, 1240, 953);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_yazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_yazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_yazarActionPerformed

    private void tf_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_stokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_stokActionPerformed

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        DefaultTableModel model1 = (DefaultTableModel) urun_tablosu1.getModel();
        if (tf_urun_ismi.getText().trim().equals("")) {

            mesaj_yazisi.setText("Kitap ismi boş bırakılamaz...");
        }
        else {
            Object[] eklenecek = {tf_urun_ismi.getText(),cb_kategori.getSelectedItem().toString(),tf_yazar.getText(),tf_stok.getText()};
            mesaj_yazisi.setText("Kitap başarıyla eklendi");
            model.addRow(eklenecek);
        }
        if (tf_urun_ismi.getText().trim().equals("")) {

            mesaj_yazisi.setText("Kitap ismi boş bırakılamaz...");
        }
        else {
            Object[] eklenecek = {tf_urun_ismi.getText(),cb_kategori.getSelectedItem().toString(),tf_yazar.getText(),tf_stok.getText()};
            mesaj_yazisi.setText("Kitap başarıyla eklendi");
            model1.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        mesaj_yazisi.setText("");

        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        DefaultTableModel model1 = (DefaultTableModel) urun_tablosu1.getModel();

        int secili_row = urun_tablosu.getSelectedRow();

        if (secili_row == -1) {

            if (urun_tablosu.getRowCount() == 0 ) {

                mesaj_yazisi.setText("Kitap tablosu şu anda boş....");
            }
            else {

                mesaj_yazisi.setText("Lütfen güncellenecek bir kitap seçin...");
            }
        }
        else {

            model.setValueAt(tf_urun_ismi.getText(),secili_row,0);
            model.setValueAt(cb_kategori.getSelectedItem().toString(),secili_row,1);
            model.setValueAt(tf_yazar.getText(),secili_row,2);
            model.setValueAt(tf_stok.getText(),secili_row,3);

            mesaj_yazisi.setText("Kitap başarıyla güncellendi...");

        }
        if (secili_row == -1) {

            if (urun_tablosu1.getRowCount() == 0 ) {

                mesaj_yazisi.setText("Kitap tablosu şu anda boş....");
            }
            else {

                mesaj_yazisi.setText("Lütfen güncellenecek bir kitap seçin...");
            }
        }
        else {

            model1.setValueAt(tf_urun_ismi.getText(),secili_row,0);
            model1.setValueAt(cb_kategori.getSelectedItem().toString(),secili_row,1);
            model1.setValueAt(tf_yazar.getText(),secili_row,2);
            model1.setValueAt(tf_stok.getText(),secili_row,3);

            mesaj_yazisi.setText("Kitap başarıyla güncellendi...");

        }

    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
        mesaj_yazisi.setText("");

        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        DefaultTableModel model1 = (DefaultTableModel) urun_tablosu1.getModel();

        int secili_row = urun_tablosu.getSelectedRow();

        if (secili_row == -1) {
            if (urun_tablosu.getRowCount() == 0 ) {

                mesaj_yazisi.setText("Kitap tablosu şu anda boş...");
            }
            else {

                mesaj_yazisi.setText("Lütfen silinecek bir kitap seçin...");
            }
        }
        else {

            model.removeRow(secili_row);

            mesaj_yazisi.setText("Kitap başarıyla silindi...");
        }

        if (secili_row == -1) {
            if (urun_tablosu1.getRowCount() == 0 ) {

                mesaj_yazisi.setText("Kitap tablosu şu anda boş...");
            }
            else {

                mesaj_yazisi.setText("Lütfen silinecek bir kitap seçin...");
            }
        }
        else {

            model1.removeRow(secili_row);

            mesaj_yazisi.setText("Kitap başarıyla silindi...");
        }

    }//GEN-LAST:event_sil_butonuActionPerformed

    private void tf_aramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_aramaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_aramaActionPerformed

    private void tf_aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_aramaKeyReleased
        String searchString = tf_arama.getText();
        search(searchString);
    }//GEN-LAST:event_tf_aramaKeyReleased

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();

        int secili_row = urun_tablosu.getSelectedRow();

        tf_urun_ismi.setText(model.getValueAt(secili_row,0).toString());
        cb_kategori.setSelectedItem(model.getValueAt(secili_row,1).toString());
        tf_yazar.setText(model.getValueAt(secili_row,2).toString());
        tf_stok.setText(model.getValueAt(secili_row,3).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        jTabbedPane1.setSelectedIndex(0);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
jTabbedPane1.setSelectedIndex(1);
       
    }//GEN-LAST:event_jLabel4MouseClicked

    private void urun_tablosu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosu1MouseClicked

    }//GEN-LAST:event_urun_tablosu1MouseClicked

    private void tf_arama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_arama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_arama1ActionPerformed

    private void tf_arama1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_arama1KeyReleased
        String searchString = tf_arama1.getText();
        search(searchString);
    }//GEN-LAST:event_tf_arama1KeyReleased

    private void btn_iadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iadeActionPerformed
        mesaj_yazisi1.setText("");

        DefaultTableModel model = (DefaultTableModel) odunc_tablo.getModel();
        DefaultTableModel model1 = (DefaultTableModel) odunc_tablo.getModel();

        int secili_row = odunc_tablo.getSelectedRow();

        if (secili_row == -1) {
            if (odunc_tablo.getRowCount() == 0 ) {

                mesaj_yazisi1.setText("Ödünç takip  tablosu şu anda boş...");
            }
            else {

                mesaj_yazisi1.setText("Lütfen iade edilecek kitabı seçiniz...");
            }
        }
        else {

            model.removeRow(secili_row);

            mesaj_yazisi1.setText("Kitap iade edildi...");
        }
    }//GEN-LAST:event_btn_iadeActionPerformed

    private void btn_oduncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oduncActionPerformed
        SimpleDateFormat dateformat =new SimpleDateFormat("yyyy-MM-dd");
        String theDate =dateformat.format(date1.getDate());

        mesaj_yazisi1.setText("");
        DefaultTableModel model = (DefaultTableModel) odunc_tablo.getModel();
        DefaultTableModel model2= (DefaultTableModel) urun_tablosu1.getModel();
        DefaultTableModel model3= (DefaultTableModel) urun_tablosu.getModel();

        if (tf_kitap1.getText().trim().equals("")) {

            mesaj_yazisi1.setText("Kitap ismi boş bırakılamaz...");
        }
        else {
            Object[] eklenecek = {tf_kitap1.getText(),tf_yazar1.getText(),cb_kategori1.getSelectedItem().toString(),date1.getDate(),date2.getDate()};

            mesaj_yazisi1.setText("Kitap başarıyla ödünç alındı");
            model.addRow(eklenecek);

        }

    }//GEN-LAST:event_btn_oduncActionPerformed

    private void tf_kitap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kitap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kitap1ActionPerformed

    private void tf_yazar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_yazar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_yazar1ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void kullanici_tbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanici_tbMouseReleased

    }//GEN-LAST:event_kullanici_tbMouseReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anasayfa;
    private javax.swing.JButton btn_iade;
    private javax.swing.JButton btn_odunc;
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JComboBox<String> cb_kategori1;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel kullanici;
    private javax.swing.JTable kullanici_tb;
    private javax.swing.JPanel kutuphane;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JLabel mesaj_yazisi1;
    private javax.swing.JTable odunc_tablo;
    private javax.swing.JPanel oduncal;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField tf_arama;
    private javax.swing.JTextField tf_arama1;
    private javax.swing.JTextField tf_kitap1;
    private javax.swing.JTextField tf_stok;
    private javax.swing.JTextField tf_urun_ismi;
    private javax.swing.JTextField tf_yazar;
    private javax.swing.JTextField tf_yazar1;
    private javax.swing.JTable urun_tablosu;
    public javax.swing.JTable urun_tablosu1;
    // End of variables declaration//GEN-END:variables
}
