
package otomasyon.kutuphane;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

class User{
    
    private String kullanici_adi;
    private String parola;

    public User(String kullanici_adi, String parola) {
        this.kullanici_adi = kullanici_adi;
        this.parola = parola;
    }

    public String getKullanici_adi() {
        return kullanici_adi;
    }

    public void setKullanici_adi(String kullanici_adi) {
        this.kullanici_adi = kullanici_adi;
    }

    public String getParola() {
        return parola;
    }

    public void setParola(String parola) {
        this.parola = parola;
    }
    
}
public class login extends javax.swing.JFrame {
    static ArrayList<User> user_list = new ArrayList<User>();

    public static ArrayList<User> getUser_list() {
        return user_list;
    }

    public static void setUser_list(ArrayList<User> user_list) {
        
    }

    
    
    
    /**
     * Creates new form register
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kullanici_adi_alani = new javax.swing.JTextField();
        giris = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        parola_alani = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Parola:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setText("Kullanıcı adı:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        kullanici_adi_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_adi_alaniActionPerformed(evt);
            }
        });
        jPanel1.add(kullanici_adi_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 230, 40));

        giris.setBackground(new java.awt.Color(14, 151, 137));
        giris.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        giris.setForeground(new java.awt.Color(255, 255, 255));
        giris.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-login-50.png")); // NOI18N
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });
        jPanel1.add(giris, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 100, 50));

        jPanel2.setBackground(new java.awt.Color(14, 151, 137));
        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-book-50.png")); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 90, 70, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Sistemimize Hoş geldiniz! ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 30, 222, 25);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Kayıt olmak için  kayıt ol ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 180, 214, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("butonuna basınız.");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 230, 152, 25);

        register.setBackground(new java.awt.Color(248, 240, 240));
        register.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-register-64 (1).png")); // NOI18N
        register.setText("Kayıt ol");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel2.add(register);
        register.setBounds(40, 320, 170, 60);

        jButton1.setBackground(new java.awt.Color(248, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mcahi\\OneDrive\\Masaüstü\\kütüphane otomasyon\\kutuphane\\src\\main\\java\\otomasyon\\kutuphane\\icons8-exit-48.png")); // NOI18N
        jButton1.setText("Çıkış");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(40, 410, 170, 60);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 490));
        jPanel1.add(parola_alani, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullanici_adi_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_adi_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullanici_adi_alaniActionPerformed

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
         String kullanici_adi = kullanici_adi_alani.getText();
         String parola = new String(parola_alani.getPassword());
         if (user_list.size() == 0 ) {
             JOptionPane.showMessageDialog(login.this,"Hiçbir kullanıcı bulunmamaktadır.\nLütfen önce kayıt olun.");
         }
         else {
         for (User user : user_list) {
             if (user.getKullanici_adi().equals(kullanici_adi) && user.getParola().equals(parola)) {
                 JOptionPane.showMessageDialog(login.this,"Giriş Başarılı,Hoşgeldin "+kullanici_adi);
                 new anasayfa().setVisible(true);
             }
             else {
                 JOptionPane.showMessageDialog(login.this,"Giriş Başarısız. Lütfen önce kayıt olun.");
             }
             
         }
         }
         
    }//GEN-LAST:event_girisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        new register().setVisible(true);

    }//GEN-LAST:event_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton giris;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField kullanici_adi_alani;
    private javax.swing.JPasswordField parola_alani;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables



}
